name:                chess-server
version:             0.1.0.0
github:              "githubuser/chess-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/chess-server#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - network >= 2.6.3.5
  - aeson >= 1.2.4.0
  - random >= 1.1
  - deepseq >= 1.4.3.0
  - containers >= 0.5.10.0
  - time >= 1.8
  - bytestring >= 0.10
  - unix >= 2.7
  - parallel >= 3.2

executables:
  chess-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      #    - -threaded
      #- -rtsopts
      #- -with-rtsopts=-N
    dependencies:
    - chess-server

tests:
  chess-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chess-server
